name: Valist Publish
on:
  push:
    branches:
      - main
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and export Next.js app
        run: |
           npm install
           npm run build && npx next export

      - name: Mark Timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        
      - name: Valist Publish
        uses: valist-io/valist-github-action@v2.3.1
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: webgame
          project: game
          release: ${{ env.TIMESTAMP }}
          path: out